title: Gramabharathi 
email: org.gramabharathi@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Gramabharathi vission is to protecting the Traditional Wealth like Soil Wealth(Bhoo Sampadha), Cow Wealth(Gow Sampadha), Forest Wealth(Vana Sampadha),
  Water Wealth(Jala Sampadha), Human Resources(Jana Sampadha), Bio Deversity(Jeeva Sampadha), Natural Energies(Urja Sampadha - Tidal, Hydal, Wind and Solar Poser)
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username:  jekyll
paginate: 5
paginate_path: /page:num/
permalink: /:categories/:title/

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Authors
authors:
  balu:
    name: Jinna Balu
    display_name: Jinna Balu
    gravatar: 24b94c438636e3d95a32f72999d5081f
    email: jinna.balu@outllok.com
    web: https://jinnabalu.github.io
    twitter: https://twitter.com/JinnaBalu
    twitter_username: JinnaBalu
    description: "Platform Engineer @ Wisestep Inc, Developer and maintainer of Platform Ops"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
