# Site
name: "Grama Bharathi"
title: "Grama Bharathi"
description: >- # this means to ignore newlines until "baseurl:"
  Gramabharathi vission is to protecting the Traditional Wealth like Soil Wealth(Bhoo Sampadha), Cow Wealth(Gow Sampadha), Forest Wealth(Vana Sampadha),
  Water Wealth(Jala Sampadha), Human Resources(Jana Sampadha), Bio Deversity(Jeeva Sampadha), Natural Energies(Urja Sampadha - Tidal, Hydal, Wind and Solar Poser)
meta_description: >- # this means to ignore newlines until "baseurl:"
  Gramabharathi vission is to protecting the Traditional Wealth like Soil Wealth(Bhoo Sampadha), Cow Wealth(Gow Sampadha), Forest Wealth(Vana Sampadha),
  Water Wealth(Jala Sampadha), Human Resources(Jana Sampadha), Bio Deversity(Jeeva Sampadha), Natural Energies(Urja Sampadha - Tidal, Hydal, Wind and Solar Poser)
logo: 'assets/images/logo-sm.jpg'
nav_logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.png'
paginate: 8
baseurl: ''
email: 'jinna.balu@outllok.com'
google_analytics: 'UA-144977506-1'
disqus: 'grama-bharathi'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5d413865ee1138001128e66b&product=sticky-share-buttons"></script>'

# Authors
authors:
  balu:
    name: Jinna Balu
    display_name: Jinna Balu
    gravatar: 24b94c438636e3d95a32f72999d5081f
    email: jinna.balu@outllok.com
    web: https://jinnabalu.github.io
    twitter: https://twitter.com/JinnaBalu
    twitter_username: JinnaBalu
    description: "Platform Engineer @ Wisestep Inc, Developer and maintainer of Platform Ops"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge